imports:
  - { resource: services/admin.yml }
  - { resource: services/search.yml }
  - { resource: services/routing.yml }
  - { resource: services/field.yml }
  - { resource: services/field_text.yml }
  - { resource: services/field_number.yml }
  - { resource: services/field_choice.yml }
  - { resource: services/field_boolean.yml }
  - { resource: services/field_reference.yml }

services:

  #
  # Doctrine - Map node listener
  gravity_node.doctrine.node_listener:
    class: Gravity\CmsBundle\Doctrine\EventListener\NodeEventListener
    arguments:
      - @security.token_storage
      - @gravity_cms.routing.node_route_builder
    tags:
      - { name: doctrine.event_subscriber }

  # Revision Listener
  #gravity_node.doctrine.revision_listener:
  #  class: Gravity\CmsBundle\Doctrine\EventListener\RevisionEventListener
  #  arguments:
  #    - @gravity_cms.field_manager
  #  tags:
  #    - { name: doctrine.event_subscriber }

  #
  # form
  gravity_cms.form.type.autocomplete:
    class: Gravity\CmsBundle\Form\Type\AutoCompleteType
    arguments:
      - @gravity_cms.search.handler_manager
      - @router.default
    tags:
      - { name: form.type, alias: auto_complete }

  gravity_cms.form.type.hidden_entity:
    class: Gravity\CmsBundle\Form\Type\HiddenEntityIdType
    arguments:
      - @doctrine.orm.default_entity_manager
    tags:
      - { name: form.type, alias: hidden_entity }
