services:
  gravity_cms.form.type.gravity_media_type:
    class: Gravity\MediaBundle\Form\MediaType
    arguments:
      - @sonata.media.pool
      - ~
    tags:
      - { name: form.type, alias: gravity_media_type }

  gravity_cms.field.reference.media:
    class: Gravity\MediaBundle\Field\Type\Reference\MediaField
    tags:
      - { name: gravity_cms.field }

  gravity_cms.field.reference.widget.sonata_media:
    class: Gravity\MediaBundle\Field\Type\Reference\Widget\SonataMedia\SonataMediaWidget
    tags:
      - { name: gravity_cms.field.widget }

  gravity_cms.field.reference.widget.gravity_media:
    class: Gravity\MediaBundle\Field\Type\Reference\Widget\GravityMedia\GravityMediaWidget
    tags:
      - { name: gravity_cms.field.widget }

  gravity_cms.field.reference.display.media_sonata:
    class: Gravity\MediaBundle\Field\Type\Reference\Display\SonataMediaDisplay
    tags:
      - { name: gravity_cms.field.display }


  gravity_cms.serializer.event_subscriber.meida:
    class: Gravity\MediaBundle\Serializer\EventDispatcher\MediaEventSubscriber
    arguments:
      - @sonata.media.pool
    tags:
      - { name: jms_serializer.event_subscriber }
